---
title: How about MathJax?
author: Gabi Huiber
date: '2017-09-24'
slug: how-about-mathjax
categories: []
tags: []
---

The default Lithium theme in blogdown comes with MathJax support. This big Sigma here -- $\Sigma$ -- will show like the Greek upper case Sigma if you have it.

This seems driven by a script called `math-code.js` here:

```{r showMathCode}
library('here')
dir(file.path(here(), 'themes/hugo-lithium-theme/static/js'))
dir(file.path(here(), 'themes/ghostwriter/static/js'))
dir(file.path(here(), 'themes/minimal/static'))
```
So, it seems like I could just copy this script to Ghostwriter's `static/js` folder, and copy the whole `js` folder to Minimal's `static` folder, like so (at the command line):

```
cp themes/hugo-lithium-theme/static/js/math-code.js themes/ghostwriter/static/js/
cp -R themes/hugo-lithium-theme/static/js themes/minimal/static/
```

In addition, I'll have to edit the other themes' respective `config.toml` files with some extra parameters, so I will first make sure that the originals are preserved:

```
cp themes/ghostwriter/exampleSite/config.toml themes/ghostwriter/exampleSite/config_example.toml
cp themes/minimal/exampleSite/config.toml themes/minimal/exampleSite/config_example.toml
```

Then I'll copy over this section of the `[params]` block from the Lithium `config.toml` file to the `[params]` block in each of the other themes' own `config.toml` file. Notice that this block handles both code highlighting and MathJax. Might as well take care of both in one fell swoop.

If this screws anything up, I'll just revert to the `config_example.toml` that I saved:

```
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
```

But we're not done yet. In addition to the `math-code.js` script in the `static/js` folder and the parameters in `config.toml`, Hugo needs to see these pieces called from inside one of the html files in `layouts/partials`. 

## How does Lithium do it?

The Lithium theme has `footer_mathjax.html`, `footer_highlightjs.html` and `header_highlightjs.html` in the `partials` folder.

Here's the bottom of `themes/hugo-lithium-theme/layouts/partials/footer.html`:

```
    {{ partial "footer_highlightjs" . }}
    {{ partial "footer_mathjax" . }}
    {{ template "_internal/google_analytics.html" . }}
  </body>
</html>
```

And here's the bottom of `themes/hugo-lithium-theme/layouts/partials/head.html`:

```
{{ partial "head_highlightjs" . }}
<link rel="stylesheet" href="{{ "css/fonts.css" | relURL }}" media="all">
<link rel="stylesheet" href="{{ "css/main.css" | relURL }}" media="all">
{{ range .Site.Params.customCSS }}
<link rel="stylesheet" href="{{ . | relURL }}">
{{ end }}
{{ partial "head_custom" . }}
```

This `head.html` file is called inside the `<head></head>` tags of `header.html` with a partial call. Here's that file: 

```
<!DOCTYPE html>
<html lang="{{ .Site.LanguageCode }}">
  <head>
    {{ partial "head.html" . }}
  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        {{ partial "nav.html" . }}
      </header>
```

So: the code in `head_highlightsjs.html` needs to make its way into the head section of `header.html` and the Lithium theme is doing this through an indirect call: `header.html` calls `head.html` which then calls `head_highlightjs.html`. OK.

## How might Ghostwriter do it?

The Ghostwriter theme handles calls to its own .js files from inside `footer.html`. Here's the bottom of `themes/ghostwriter/layouts/partials/footer.html`:
```
        <script src="{{ .Site.BaseURL }}js/scripts.js"></script>
    </body>
</html>
```

So I could replace the above with
```
        <script src="{{ .Site.BaseURL }}js/scripts.js"></script>
        {{ partial "footer_highlightjs" . }}
        {{ partial "footer_mathjax" . }}
    </body>
</html>
```

And then 

  - `cp themes/hugo-lithium-theme/layouts/partials/footer_mathjax.html themes/ghostwriter/layouts/partials/footer_mathjax.html` and 
  - `cp themes/hugo-lithium-theme/layouts/partials/footer_highlightjs.html themes/ghostwriter/layouts/partials/footer_highlightjs.html`

I will `cp` the `head_highlightjs.html` partial into the Ghostwriter partials folder in the same way. I also need to make a call to it from Ghostwriter's own `header.html` partial and make it inside the `<head></head>` tags. So here's the relevant piece of `themes/ghostwriter/layouts/partials/header.html`:
```
        {{ if .RSSLink }}
            <link href="{{ .RSSLink }}" rel="alternate" type="application/rss+xml">
        {{ end }}
    </head>
```

And I'm going to change it to
```
        {{ if .RSSLink }}
            <link href="{{ .RSSLink }}" rel="alternate" type="application/rss+xml">
        {{ end }}
        {{ partial "head_highlightjs" . }}
    </head>
```

This works, with the annoying issue that now I have these html files from one theme copied into a submodule. If the main theme is ever updated and these files change, I'll have to remember to copy them over.

## How about Minimal?

The Minimal theme -- which didn't come with a `static/js` folder of its own -- has a `js.html` file that calls some .js files from various locations on the internets. So, I could use the same procedure: copy over three partials, call two of them from the footer, one from the header. And, that worked!